apiVersion: v1
kind: Service
metadata:
  name: {{ include "ns-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ns-webapp.name" . }}
    helm.sh/chart: {{ include "ns-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - nodePort: {{ .Values.service.externalPort }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "ns-webapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
